create database minorproject;
use minorproject;
#drop table membersofcollege;
#drop table hostels;
#drop table student;
#drop table grade;
create table membersofcollege(ID int not null,Name varchar(255),password varchar(10),usertype varchar(255),primary key(ID));
create table student(Roll_no int not null,primary key(roll_no),Name varchar(255),Address varchar(255),Department varchar(255),foreign key(Department) references Department(Department_Name),Year int,Phone_Number varchar(255),Faculty_Advisor_id int,foreign key(Faculty_Advisor_id) references faculty(ID),caterer_id int,foreign key(caterer_id) references caterer(ID),clubs_id varchar(255),cpi float,currspi float);
create table course(course_code int not null,Name varchar(255),credits float,Department varchar(255),primary key(course_code),foreign key(Department) references Department(Department_Name));
create table Department(Department_Name varchar(255),HOD int,primary key(Department_Name),foreign key(HOD) references membersofcollege(ID));
create table faculty(ID int not null,Name varchar(255),Specialization varchar(255),Department varchar(255),Role varchar(255),Courses int,Salary int not null,primary key(ID),foreign key(Department) references Department(Department_Name));
create table hostels(hostel_id int not null,hostel_name varchar(255),warden_id int,capacity int not null,primary key(hostel_id),foreign key(warden_id) references membersofcollege(id));
create table staff(ID int not null,Name varchar(255),contact_number varchar(255),Salary int not null,work varchar(255),work_place int not null,primary key(ID),foreign key(work_place) references hostels(hostel_id)); 
create table Clubs(Name varchar(255),primary key(Name),mentor int,foreign key(mentor) references faculty(ID),fund_id int,Strength int,Head int,foreign key(Head) references membersofcollege(ID));
create table funds(id int,primary key(id),Amount int,granted_to varchar(255),status varchar(10));
create table grade(course_id int,grade int,student_id int,foreign key(course_id) references course(course_code),foreign key(student_id) references student(Roll_no)) ;
create table caterer(ID int,primary key(ID),Name varchar(255),capacity int,Charges int);
create table projects(Project_id int,primary key(Project_id),About varchar(255),fund_id int,foreign key(fund_id) references funds(id),Supervisor int,foreign key(Supervisor) references faculty(ID),strength int);
create table Interns(ID int,primary key(ID),year int,phone_number varchar(255),project_id int,foreign key(project_id) references projects(Project_id),name varchar(255),salary int);
create table Health_Appointments(Appointment_no int, primary key(Appointment_no),Doctor_id int,foreign key(Doctor_id) references Doctors(id),description varchar(255),pateint_id int,foreign key(pateint_id) references membersofcollege(ID));
create table Doctors(id int,primary key(id),specialization varchar(255),Name varchar(255),contact_number varchar(255));